name: Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Unit Test Cover
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov
        /p:CoverletOutput='/home/runner/work/qpmodel/qpmodel/test/lcov.info'
        /p:ExcludeByFile=\"**/qpmodel/program.cs,**/psql/**/*.cs,**/psql/*.cs,**/qpmodel/obj/**/*.cs\"
    - name: Coveralls
      uses: coverallsapp/github-action@v2
      continue-on-error: true
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        file: "/home/runner/work/qpmodel/qpmodel/test/lcov.info"
